import os
import sys
import tkinter as tk
from tkinter import messagebox

from gui.main_window import MainApp

# Define the path for the custom CA certificate.
# The mitmproxy CA files will be stored in a hidden directory ~/.mitmproxy
# We will point our app to use the default cert generated by mitmproxy.
CERT_DIR = os.path.expanduser("~/.mitmproxy")
CERT_FILE = os.path.join(CERT_DIR, "mitmproxy-ca.pem")

def check_and_generate_cert():
    """
    Checks for the mitmproxy CA certificate.
    If it doesn't exist, it guides the user on how to generate it.
    """
    if not os.path.exists(CERT_FILE):
        # In a real scenario, we would trigger mitmproxy's cert generation.
        # For now, we assume mitmproxy has been run once to generate the certs.
        # We will provide instructions in the README.
        messagebox.showinfo(
            "Certificate Not Found",
            f"Welcome! To intercept HTTPS traffic, you need to install a root certificate.\n\n"
            f"It seems the certificate is not found at:\n{CERT_FILE}\n\n"
            f"Please run 'mitmproxy' once from your terminal to generate it, then restart this tool. "
            f"Detailed instructions are in README.md."
        )
        # In a more advanced version, we could run the command for the user.
        # For now, exiting is the simplest way to ensure the user takes action.
        sys.exit(1)
    
    return True

def main():
    """
    Main function to start the application.
    """
    # 1. Check for the CA certificate.
    check_and_generate_cert()

    # 2. Set up and run the GUI.
    root = tk.Tk()
    app = MainApp(root)
    
    try:
        root.mainloop()
    except KeyboardInterrupt:
        print("\nCtrl+C detected, shutting down.")
        app.shutdown()

if __name__ == "__main__":
    main()
